
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amamune
 */
public class GameMode extends javax.swing.JFrame {

    /**
     * Creates new form GameMode
     */
    public GameMode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttEasy = new javax.swing.JButton();
        bttMed = new javax.swing.JButton();
        bttHard = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matsing Type");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setIconImages(null);
        setLocation(new java.awt.Point(420, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttEasy.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        bttEasy.setForeground(new java.awt.Color(51, 153, 0));
        bttEasy.setText("EASY");
        bttEasy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttEasy.setBorderPainted(false);
        bttEasy.setContentAreaFilled(false);
        bttEasy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEasyActionPerformed(evt);
            }
        });
        getContentPane().add(bttEasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 144, 34));

        bttMed.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        bttMed.setForeground(new java.awt.Color(255, 102, 0));
        bttMed.setText("MEDIUM");
        bttMed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttMed.setBorderPainted(false);
        bttMed.setContentAreaFilled(false);
        bttMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMedActionPerformed(evt);
            }
        });
        getContentPane().add(bttMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 144, -1));

        bttHard.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        bttHard.setForeground(new java.awt.Color(255, 0, 0));
        bttHard.setText("HARD");
        bttHard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttHard.setBorderPainted(false);
        bttHard.setContentAreaFilled(false);
        bttHard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHardActionPerformed(evt);
            }
        });
        getContentPane().add(bttHard, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 144, 34));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bananamed.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 120, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banana.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 120, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bananahard.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setText("CHOOSE DIFFICULTY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK TO MAIN MENU");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, 39));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow11.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 230, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mon.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bana.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHardActionPerformed
      this.dispose();
     hard h = new hard();
     h.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_bttHardActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
     Menu men = new Menu();
     men.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bttMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMedActionPerformed
        this.dispose();
       Medium m = new Medium();
       m.setVisible(true);
       
    }//GEN-LAST:event_bttMedActionPerformed

    private void bttEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEasyActionPerformed
       this.dispose();
       
       Easy e = new Easy();
       
       e.setVisible(true);
    }//GEN-LAST:event_bttEasyActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
       jButton1.setForeground(Color.orange);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       GameMode gm = new GameMode();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttEasy;
    private javax.swing.JButton bttHard;
    private javax.swing.JButton bttMed;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
