
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class hard extends javax.swing.JFrame {
private static boolean run = true;
 int counter;   
    public hard() {
        
        initComponents();
        
            
        Timer t = new Timer();
         counter = 5;
        TimerTask task = new TimerTask(){
            public void run(){
                if(run){
                silip.setText(Integer.toString(counter));
                counter--; 
                

                }
                if(counter == -1){
                    this.cancel();
                    run = false;
                    
            boolean x=true;
            long displayMinutes=3;
            long starttime=0;
            long timepassed=0;
             long secondspassed=starttime-timepassed;
            while(x)
            {
            try {
                TimeUnit.SECONDS.sleep(1);
                
               
                if(displayMinutes>0&&secondspassed==0){
                    displayMinutes--;
                    secondspassed=59;
                }
                   
                else if(secondspassed<60)
                {
                    
                    secondspassed--;
                    
                    //starttime=System.currentTimeMillis();
                }
                
                
                if(displayMinutes==0&&secondspassed==0){
                    x=false;
                    gameover r = new gameover();
                   
                    r.setVisible(true);
                    exit();
                }
                
                rem_time.setText(displayMinutes+":"+secondspassed);
                     } catch (InterruptedException ex) {
                Logger.getLogger(Easy.class.getName()).log(Level.SEVERE, null, ex);
                      }
                 }
                }
                System.out.println(counter);
                
            }

            
        };
        t.scheduleAtFixedRate(task,1000,1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        silip = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        rem_time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        monkeyAng = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 10));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        silip.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        silip.setText("0");
        getContentPane().add(silip, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("GIVE UP");
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Silip time:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        score2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        score2.setForeground(new java.awt.Color(255, 255, 255));
        score2.setText("0");
        getContentPane().add(score2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("8");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 60, 60));

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("7");
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 60, 60));

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("8");
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 60, 60));

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("3");
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 60, 60));

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("3");
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 60, 60));

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("2");
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 60, 60));

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("6");
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 60, 60));

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("7");
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 60, 60));

        rem_time.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rem_time.setForeground(new java.awt.Color(255, 255, 255));
        rem_time.setText("0");
        getContentPane().add(rem_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("POINTS:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 60, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("5");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 60, 60));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("4");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 60, 60));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("2");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 60, 60));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("1");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 60, 60));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("5");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 60, 60));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("4");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 60, 60));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("6");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 60, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MATSING TYPE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 26, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("8");
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 60, 60));

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("7");
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 60, 60));

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("8");
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 60, 60));

        jButton21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("6");
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 60, 60));

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("1");
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 60, 60));

        jButton23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("5");
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 60, 60));

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("4");
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 60, 60));

        jButton25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("6");
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 60, 60));

        jButton26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("6");
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 60, 60));

        jButton27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("7");
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 60, 60));

        jButton28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("8");
        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 60, 60));

        jButton29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("6");
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 60, 60));

        jButton30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("6");
        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        jButton30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 60, 60));

        jButton31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("8");
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 60, 60));

        jButton32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("1");
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 60, 60));

        jButton33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("5");
        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        jButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 60, 60));

        jButton34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("4");
        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        jButton34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 60, 60));

        jButton35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("6");
        jButton35.setBorderPainted(false);
        jButton35.setContentAreaFilled(false);
        jButton35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 60, 60));

        jButton36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText("6");
        jButton36.setBorderPainted(false);
        jButton36.setContentAreaFilled(false);
        jButton36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 60, 60));

        jButton37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("6");
        jButton37.setBorderPainted(false);
        jButton37.setContentAreaFilled(false);
        jButton37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 60, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button33.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 150, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel13.setText("jLabel7");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 60, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel14.setText("jLabel7");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 60, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel15.setText("jLabel7");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 60, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel16.setText("jLabel7");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 60, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel17.setText("jLabel7");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 60, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel18.setText("jLabel7");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 60, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel31.setText("jLabel7");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 60, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel32.setText("jLabel7");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 60, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel33.setText("jLabel7");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 60, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel34.setText("jLabel7");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 60, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel35.setText("jLabel7");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 60, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel36.setText("jLabel7");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 60, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel37.setText("jLabel7");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 60, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel38.setText("jLabel7");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 60, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel39.setText("jLabel7");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 60, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel40.setText("jLabel7");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 60, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel41.setText("jLabel7");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 60, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel42.setText("jLabel7");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 60, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel43.setText("jLabel7");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 60, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel44.setText("jLabel7");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 60, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel45.setText("jLabel7");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 60, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel46.setText("jLabel7");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 60, -1));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel47.setText("jLabel7");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 60, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel48.setText("jLabel7");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 60, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel49.setText("jLabel7");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 60, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel50.setText("jLabel7");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 60, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel51.setText("jLabel7");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 60, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel52.setText("jLabel7");
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 60, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel53.setText("jLabel7");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 60, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel54.setText("jLabel7");
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 60, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel55.setText("jLabel7");
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 60, -1));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel56.setText("jLabel7");
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 60, -1));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel57.setText("jLabel7");
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 60, -1));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel58.setText("jLabel7");
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 60, -1));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel59.setText("jLabel7");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 60, -1));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square222.png"))); // NOI18N
        jLabel60.setText("jLabel7");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 60, -1));

        monkeyAng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/angry1.png"))); // NOI18N
        getContentPane().add(monkeyAng, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button1.png"))); // NOI18N
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button2.png"))); // NOI18N
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, 60));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/title5.png"))); // NOI18N
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void exit(){
        this.dispose();
    }
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       gameover r = new gameover();
       
       this.dispose();
       r.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel monkeyAng;
    private javax.swing.JLabel rem_time;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel silip;
    // End of variables declaration//GEN-END:variables
}
